//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_VP
{
    using System;
    using System.Collections.Generic;
    
    public partial class hall_showtime
    {
        public int showtime_id { get; set; }
        public int hall_id { get; set; }
        public int hsh_id { get; set; }
        public string seat_map { get; set; }
    
        public virtual hall hall { get; set; }
        public virtual showtime showtime { get; set; }
    }
}
