//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_VP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cinemaEntities2 : DbContext
    {
        public cinemaEntities2()
            : base("name=cinemaEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hall> halls { get; set; }
        public virtual DbSet<hall_showtime> hall_showtime { get; set; }
        public virtual DbSet<movie> movies { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<showtime> showtimes { get; set; }
        public virtual DbSet<ticket> tickets { get; set; }
    }
}
