//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_VP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public int ticket_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public string seat { get; set; }
        public int showtime_id { get; set; }
        public string role { get; set; }
        public Nullable<int> hall_id { get; set; }
    
        public virtual role role1 { get; set; }
        public virtual showtime showtime { get; set; }
    }
}
