//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kontrolnaya2
{
    using System;
    using System.Collections.Generic;
    
    public partial class postcard
    {
        public int postcard_id { get; set; }
        public string senser_email { get; set; }
        public string receiver_email { get; set; }
        public string picname { get; set; }
        public string text_for_postcard { get; set; }
    }
}
